# Run JUST Main.java
# Install java 19 - Parce que j'ai la version java 19 sur mon
# Se positinner dans le répertoire où se trouve Main.java
# En ligne de commande faire: javac Main.java
# Le fichier Main.class sera généré 

FROM openjdk:19

COPY Main.class .
COPY Main.java .

CMD ["java", "Main"]