---
# tasks file for roles/docker-postgres

- name: Run postgres
  docker_container:
    name: database
    state: started
    image: lucienmat/postgres-database:latest
    networks: 
     - name: app-network
    ports:
      - 5432:5432
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    volumes:
      - ./postgres:/var/lib/postgresql/data
