---
# tasks file for roles/docker-simple-api

- name: Run simple-api
  docker_container:
    name: simple-api
    image: lucienmat/simple-api:latest
    pull: yes
    networks: 
     - name: app-network
    ports:
     - 8080:8080
  